name: flutter_appchatbot
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  sqflite :
  flutter_login :
  shared_preferences:
  fluttertoast:
  hexcolor: ^1.0.6
  animate_icons: ^0.0.4
  flutter:
    sdk: flutter
  cupertino_back_gesture: ^0.0.3
  flutter_chat_bubble: ^1.0.2
  dash_chat: ^1.1.15
  emojis:
  cupertino_icons: ^1.0.0
  bubble: ^1.1.9+1
  intl:
  flutter_dialogflow: ^0.1.3
  google_fonts:
  gradient_app_bar: ^0.0.1
  flutter_sparkline: ^0.1.0
  flutter_circular_chart: ^0.1.0
  flutter_staggered_grid_view: ^0.3.2
  font_awesome_flutter: ^8.10.0
  fl_animated_linechart: ^1.1.4
  fl_chart: ^0.12.0
  flutter_gradient_colors: ^1.0.0
  flutter_launcher_icons: ^0.8.1
  flutter_splash_screen: ^0.1.0
  flutter_spinkit: ^4.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: "assets/WhiteIcon.png"
  ios: true
  android: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/google.png
    - assets/Wallpaper.png
    - assets/newagent-akoy-6c17e9e97bf2.json
    - assets/beaming_face_with_smiling_eyes.gif
    - assets/crying_face.gif
    - assets/face_screaming_in_fear.gif
    - assets/face_vomiting.gif
    - assets/face_with_steam_from_nose.gif
    - assets/smiling_face_with_heart_eyes.gif
    - assets/winking_face.gif
    - assets/hushed_face.gif

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: RobotoCondensed
     fonts:
      - asset: fonts/RobotoCondensed-Regular.ttf
      - asset: fonts/RobotoCondensed-Bold.ttf
      - asset: fonts/RobotoCondensed-BoldItalic.ttf
      - asset: fonts/RobotoCondensed-Italic.ttf
      - asset: fonts/RobotoCondensed-Light.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
